### ISSUE TITLE
Run pointfree in the browser

### ISSUE THREAD

**Issue by tfausak** [tfausak/blunt#3]
Instead of making a request on each keystroke, it makes sense to do the computation in the browser. It should be possible to use something like [GHCJS](https://github.com/ghcjs/ghcjs) to compile the pointfree library into JavaScript.

**Comment by tfausak** [comment]
Thanks to @caseywebdev for the suggestion.

**Comment by caseywebdev** [comment]
:+1:

**Comment by luite** [comment]
See http://hdiff.luite.com/tmp/pointsfree/ for a crude attempt based on the existing try-purescript example.

source here:
https://gist.github.com/luite/a60cced132d6a3eb7b18

original code:
https://github.com/ghcjs/ghcjs-examples/tree/master/try-purescript

additionally, `blunt` needs to be added to the build deps and `Pointfree` needs to be an exposed module.

**Comment by tfausak** [comment]
Wow, that's awesome! Thanks for creating a prototype so quickly. 

I'm not as excited about the 6.5 MB JavaScript file, though. Especially considering Blunt typically responds with about 100 *bytes* of text.

**Comment by caseywebdev** [comment]
Just implement it in vanilla JS :wink:

**Comment by luite** [comment]
The main culprit is the `haskell-src-exts` parser, which probably takes up most of that file. The minification script only uses closure compiler's simple optimizations, since at the time I prepared the `try-purescript` example, advanced optimizations broke something. This means that all long names from `haskell-src-exts` end up in the final result.

Fortunately the result is quite compressible, `prepare.sh` produces a 628kB `all.min.js.gz` file (627631 bytes) on my system.

Note that there is some functionality in this prototype that'd take more work to replicate in a client/server setting. While typing the computation is continually updated, existing computations aborted through an exception. When there are multiple results, they are added as they come in.

**Comment by tfausak** [comment]
I agree that the client-side approach is better. I'm not crazy about the cost of it, though. I'll have to think about it more.

**Comment by tfausak** [comment]
Ok, I think this is the right way to go. With compression and caching, I don't think the cost will be too bad. Plus I can add a manifest to make the site work entirely offline. 

Now I just need to get GHCJS installed.

**Comment by tfausak** [comment]
Well that took a solid half hour. I think GHCJS might prevent #9 from happening.

**Comment by tfausak** [comment]
I don't want to add at least a half hour of compilation to the setup process for this project. Depending on GHCJS would make development and deployment much harder. So even though I think this is a good direction to move in from the user's perspective, I can't get behind it. Thanks for your help, @luite!
